/*
 * Copyright (c) 2008, 2015, Jack J. Woehr jwoehr@softwoehr.com
 * PO Box 51, Golden, Colorado 80402-0051 USA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *         notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *         notice, this list of conditions and the following disclaimer
 *         in the documentation and/or other materials provided with the
 *         distribution.
 *     * Neither the name of the PigIron Project nor the names of its
 *         contributors may be used to endorse or promote products derived
 *         from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Autogenerated Mon Jan  4 02:27:38 UTC 2016
 * by pigbuilderfunc.m4 Copyright *C* 2015 Jack J. Woehr
 * Part of the PigIron Project http://pigiron.sourceforge.net
 */
package com.softwoehr.piglet.builder.functions;


/**
 * <tt>Image_Volume_Add</tt> VSMAPI Function
 *
 */
public class ImageVolumeAdd extends BuilderFunctionProxy {


    /**
     * Constructor does nothing.
     */ 
    public ImageVolumeAdd() { super();}

    /**
     *  Gets the parameters array for this BuilderFunctionProxy extender
     *
     * @return    The parameters that need form building and filling in
     */ 
    public Parameter [] getParameters() {
        return new Parameter [] {
            new Parameter("target_identifier", "", "Target of operation"),
            new Parameter("image_device_number", "*", "The virtual device number of the device"),
            new Parameter("image_vol_id", "*", "The DASD volume label"),
            new Parameter("system_config_name", "*", "File name of system configuration file - default is SYSTEM"),
            new Parameter("system_config_type", "*", "File type of system configuration file - default is CONFIG"),
            new Parameter("parm_disk_owner", "*", "Owner of the parm disk - default is MAINT"),
            new Parameter("parm_disk_number", "*", "Number of the parm disk as defined in the VSMWORK1 directory"),
            new Parameter("parm_disk_password", "*", "Multiwrite password for the parm disk - default is ,"),
            new Parameter("alt_system_config_name", "*", "File name of the  alternative system configuration file"),
            new Parameter("alt_system_config_type", "*", "File type of the alternative system configuration file"),
            new Parameter("alt_parm_disk_owner", "*", "Owner of the alternative parm disk"),
            new Parameter("alt_parm_disk_number", "*", "Number of the alternative parm disk."),
            new Parameter("alt_parm_disk_password", "*", "Multiwrite password for the alternate parm disk") } ;
    }
}
