/*
 * Copyright (c) 2008, 2015, Jack J. Woehr jwoehr@softwoehr.com
 * PO Box 51, Golden, Colorado 80402-0051 USA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *         notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *         notice, this list of conditions and the following disclaimer
 *         in the documentation and/or other materials provided with the
 *         distribution.
 *     * Neither the name of the PigIron Project nor the names of its
 *         contributors may be used to endorse or promote products derived
 *         from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Autogenerated Sat Dec 19 03:56:31 UTC 2015
 * by pigbuilderfunc.m4 Copyright *C* 2015 Jack J. Woehr
 * Part of the PigIron Project http://pigiron.sourceforge.net
 */
package com.softwoehr.piglet.builder.functions;


/**
 * {@code Image_CPU_Define_DM} VSMAPI 5.4 Function
 * @since <a href="http://publib.boulder.ibm.com/infocenter/zvm/v5r4/index.jsp">VSMAPI 5.4</a>
 */
public class ImageCPUDefineDM extends BuilderFunctionProxy {


    /** Unspecified */
    public static final int BASE_CPU_UNSPECIFIED = 0;

    /** BASE */
    public static final int BASE_CPU_BASE = 1;

    /** Unspecified */
    public static final int DEDICATE_CPU_UNSPECIFIED = 0;

    /** NODEDICATE */
    public static final int DEDICATE_CPU_NODEDICATE = 1;

    /** DEDICATE */
    public static final int DEDICATE_CPU_DEDICATE = 2;

    /** Unspecified - no CRYPTO */
    public static final int CRYPTO_UNSPECIFIED = 0;

    /** ZAAP */
    public static final int CRYPTO_CRYPTO = 1;

    /**
     * Constructor does nothing.
     */ 
    public ImageCPUDefineDM() { super();}

    /**
     *  Gets the parameters array for this BuilderFunctionProxy extender
     *
     * @return    The parameters that need form building and filling in
     */ 
    public Parameter [] getParameters() {
        return new Parameter [] {
            new Parameter("target_identifier", "", "Target of operation"),
            new Parameter("cpu_address", "", "The virtual CPU address to add to the static definition of the virtual image in the hexadecimal range of 0-3F."),
            new Parameter("base_cpu", 0, "Whether this CPU defines the base virtual processor."),
            new Parameter("cpu_id", "", "The processor identification number to be stored in bits 8 through 31 of the CPU ID."),
            new Parameter("dedicate_cpu", 0, "Whether the virtual processor is to be dedicated at LOGON time to a real processor."),
            new Parameter("crypto", 0, "Whether the virtual Cryptographic Coprocessor Facility (CCF) should be defined automatically for the virtual CPU at LOGON time.") } ;
    }
}
