/*
 * Copyright (c) 2008, 2016, Jack J. Woehr jwoehr@softwoehr.com
 * PO Box 51, Golden, Colorado 80402-0051 USA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *         notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *         notice, this list of conditions and the following disclaimer
 *         in the documentation and/or other materials provided with the
 *         distribution.
 *     * Neither the name of the PigIron Project nor the names of its
 *         contributors may be used to endorse or promote products derived
 *         from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Autogenerated Sun Oct 30 06:28:37 UTC 2016
 * by pigstruct.m4 Copyright *C* 2016 Jack J. Woehr
 * Part of the PigIron Project http://pigiron.sourceforge.net
 */
package com.softwoehr.pigiron.access.paramstructs;

import com.softwoehr.pigiron.access.*;

/**
 * DirectoryEntryFormatNoStructure implements the {@code directory_entry_format_no_structure} from {@code Query_All_DM}
 * @see com.softwoehr.pigiron.functions.QueryAllDM
 * Query_All_DM has two different sorts of structures it returns
 * based on the FORMAT=YES/NO optional parameter (default=YES).
 * This structure is for FORMAT=NO.
 * The corresponding array for FORMAT=YES is DirectoryEntryStructure
 */
public class DirectoryEntryFormatNoStructure extends VSMStruct {

    /** USER */
    public static final int DIRECTORY_ENTRY_TYPE_USER = 0;
    /** PROFILE */
    public static final int DIRECTORY_ENTRY_TYPE_PROFILE = 1;
    /** USER_DEFINED_VIA_POOL */
    public static final int DIRECTORY_ENTRY_TYPE_USER_DEFINED_VIA_POOL = 2;
    /** POOL */
    public static final int DIRECTORY_ENTRY_TYPE_POOL = 3;
    /** DIRECTORY */
    public static final int DIRECTORY_ENTRY_TYPE_DIRECTORY = 4;
    /** GLOBAL */
    public static final int DIRECTORY_ENTRY_TYPE_GLOBAL = 5;
    /** IDENTITY */
    public static final int DIRECTORY_ENTRY_TYPE_IDENTITY = 6;
    /** SUBCON */
    public static final int DIRECTORY_ENTRY_TYPE_SUBCON = 7;
    /** OTHER */
    public static final int DIRECTORY_ENTRY_TYPE_OTHER = 8;
    /**
     * Create an instance with a value derived by copying from a like instance
     * and instance its formal name at the same time.
     * null is legal value, means "just clear me and
     * re-initialize me with a valid list of yet-unread
     * parameters".
     * @param value a like instance to copy from
     * @param formalName the formal name
     * @see com.softwoehr.pigiron.access.VSMStruct
     */
    public DirectoryEntryFormatNoStructure(VSMStruct value, String formalName) {
        this(value);
        setFormalName(formalName);
    }

    /**
     * Create an instance with a value derived by copying from a like instance.
     * null is legal value, means "just clear me".
     * @param value a like instance to copy from
     */
    public DirectoryEntryFormatNoStructure(VSMStruct value) {
        super(value);
        if (value == null) {
            modelFormalParameters();
        }
    }

     /**
     * Create an instance with the formal name instanced
     * and the parameters modelled for reading.
     * @param formal_name the formal name of the instance
     */
    public DirectoryEntryFormatNoStructure(String formal_name) {
    	   super();
	   setFormalName(formal_name);
	   modelFormalParameters();
    }

    /**
     * Create a read-modelled instance.
     */
    public DirectoryEntryFormatNoStructure() {
        super();
        modelFormalParameters();
    }

    /**
     * Create an instance with all attributes instantiated
     * and instance its formal name at the same time.
     * This makes it easy to set up a VSMAPI input instance
     * of this structure.
     * @param directory_entry_type the VSMInt4 argument to the ctor
     * @param directory_entry_id the CountedString argument to the ctor
     * @param directory_entry_data_array the DirectoryEntryDataArray argument to the ctor
     * @param formalName the formal name of the data type for display/debug
     */
    public DirectoryEntryFormatNoStructure(VSMInt4 directory_entry_type, CountedString directory_entry_id, DirectoryEntryDataArray directory_entry_data_array, String formalName) {
        super();
        add(directory_entry_type);
        add(directory_entry_id);
        add(directory_entry_data_array);
        setFormalName(formalName);
    }

    /**
     * Create a read-modelled instance.
     */
    public final void modelFormalParameters() {
        clear();
        add(new VSMInt4(0, "directory_entry_type"));
        add(new CountedString("", "directory_entry_id"));
        add(DirectoryEntryDataArray.modelArray("directory_entry_data_array"));

    }
}

/* End of autogenerated code */

