/**
 * Provides the classes which embody the
 * array and structure types used in
 * VSMAPI communications. These structures
 * are compounds of the simpler parameter
 * types found in <tt>com.softwoehr.pigiron.access</tt> and are used in PigIron's
 * mapping of VSMAPI function calls. These function mappings are found in
 * <tt>com.softwoehr.pigiron.access.functions</tt>.
 *<br><br>
 * Note: All classes in this package are autogenerated by PigGen m4-based
 * description files.
 *
 * @see com.softwoehr.pigiron.access
 * @see com.softwoehr.pigiron.access.functions
 */
package com.softwoehr.pigiron.access.paramstructs;