/*
 * Copyright (c) 2008, 2015, Jack J. Woehr jwoehr@softwoehr.com
 * PO Box 51, Golden, Colorado 80402-0051 USA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *         notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *         notice, this list of conditions and the following disclaimer
 *         in the documentation and/or other materials provided with the
 *         distribution.
 *     * Neither the name of the PigIron Project nor the names of its
 *         contributors may be used to endorse or promote products derived
 *         from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Autogenerated Sun Dec 20 02:40:29 UTC 2015
 * by pigbuilderfunc.m4 Copyright *C* 2015 Jack J. Woehr
 * Part of the PigIron Project http://pigiron.sourceforge.net
 */
package com.softwoehr.piglet.builder.functions;


/**
 * {@code Asynchronous_Notification_Enable_DM} VSMAPI Function
 */
public class AsynchronousNotificationEnableDM extends BuilderFunctionProxy {


    /** Unspecified */
    public static final int ENCODING_UNSPECIFIED = 0;

    /** ASCII */
    public static final int ENCODING_ASCII = 1;

    /** EBCDIC */
    public static final int ENCODING_EBCDIC = 2;

    /** DIRECTORY */
    public static final int ENTITY_TYPE_DIRECTORY = 1;

    /** target_identifier will receive notifications for associated directory changes */
    public static final int SUBSCRIPTION_TYPE_INCLUDE = 1;

    /** target_identifier will not receive notifications for associated directory changes */
    public static final int SUBSCRIPTION_TYPE_EXCLUDE = 2;

    /** TCP */
    public static final int COMMUNICATION_TYPE_TCP = 1;

    /** UDP */
    public static final int COMMUNICATION_TYPE_UDP = 2;

    /**
     * Constructor does nothing.
     */ 
    public AsynchronousNotificationEnableDM() { super();}

    /**
     *  Gets the parameters array for this BuilderFunctionProxy extender
     *
     * @return    The parameters that need form building and filling in
     */ 
    public Parameter [] getParameters() {
        return new Parameter [] {
            new Parameter("target_identifier", "", "Target of operation"),
            new Parameter("entity_type", 0, "The entity type for which notifications will be sent."),
            new Parameter("subscription_type", 0, "The subscription type"),
            new Parameter("communication_type", 0, "The communication used for notifications"),
            new Parameter("port_number", -1, "The port number of the socket that will receive the notifications"),
            new Parameter("ip_address", "*", "he IPV4 dotted-decimal IP address of the socket that will receive the notifications."),
            new Parameter("encoding", 0, "The encoding of the notification data string"),
            new Parameter("subscriber_data", "", "Anything the subscriber wishes to receive along with the notifications") } ;
    }
}
