/*
 * Copyright (c) 2008, 2015, Jack J. Woehr jwoehr@softwoehr.com
 * PO Box 51, Golden, Colorado 80402-0051 USA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *         notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *         notice, this list of conditions and the following disclaimer
 *         in the documentation and/or other materials provided with the
 *         distribution.
 *     * Neither the name of the PigIron Project nor the names of its
 *         contributors may be used to endorse or promote products derived
 *         from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Autogenerated Tue Nov 24 05:21:07 UTC 2015
 * by pigproxfunc.m4 Copyright *C* 2015 Jack J. Woehr
 * Part of the PigIron Project http://pigiron.sourceforge.net
 */
package com.softwoehr.pigiron.webobj.topview.functions;

import com.softwoehr.pigiron.webobj.topview.*;

/**
 * Proxy function class to bridge JSON to PigIron
 *
 */
public class VirtualNetworkVswitchSet extends FunctionProxy {

    /**
     *  Create an instance of the call with empty defaults
     */
    // public VirtualNetworkVswitchSet() { super(); }

    /**
     * Create an instance of the function proxy with requestor and response instanced.
     * It will consume the requestor in execution and return the response suitably modified.
     * @param requestor the requestor spawning the instance execution
     * @param response the response to be modified and returned in the execution
     */
    public VirtualNetworkVswitchSet(Requestor requestor, Response response) throws org.json.JSONException {
        super(requestor,response);
    }

    /**
     * Execute the PigIron VSMAPI call we have set up in this instance.
     *
     * @return                             the response from the call
     * @exception  org.json.JSONException  on JSON err
     *
     * The PigIron/VSMAPI parameters fed to the instancing within execute() are as follows:
     *   --  hostname  VSMAPI Host DNS name
     *   --  port port VSMAPI Host is listening on
     *   --  userid userid executing the function
     *   --  password the password
     *   --  target_identifier the target of the VSMAPI function
     *   --  switch_name instances {@code String}
     *   --  grant_userid instances {@code String}
     *   --  user_vlan_id instances {@code String}
     *   --  revoke_userid instances {@code String}
     *   --  real_device_address instances {@code String}
     *   --  port_name instances {@code String}
     *   --  controller_name instances {@code String}
     *   --  connection_value instances {@code int}
     *   --  queue_memory_limit instances {@code int}
     *   --  routing_value instances {@code int}
     *   --  port_type instances {@code int}
     *   --  update_system_config_indicator instances {@code int}
     *   --  system_config_name instances {@code String}
     *   --  system_config_type instances {@code String}
     *   --  parm_disk_owner instances {@code String}
     *   --  parm_disk_number instances {@code String}
     *   --  parm_disk_password instances {@code String}
     *   --  alt_system_config_name instances {@code String}
     *   --  alt_system_config_type instances {@code String}
     *   --  alt_parm_disk_owner instances {@code String}
     *   --  alt_parm_disk_number instances {@code String}
     *   --  alt_parm_disk_password instances {@code String}
     *   --  gvrp_value instances {@code int}
     *   --  mac_id instances {@code String}
     */ 
    public Response execute() throws org.json.JSONException {
        com.softwoehr.pigiron.functions.VirtualNetworkVswitchSet pigfunc = new com.softwoehr.pigiron.functions.VirtualNetworkVswitchSet
	(
           getHostSpecifier()
         , host.getPortNumber()
         , user.getUid()
         , user.getPassword()
         , getTargetIdentifier()
         , getInputArgumentString("switch_name")
         , getInputArgumentString("grant_userid")
         , getInputArgumentString("user_vlan_id")
         , getInputArgumentString("revoke_userid")
         , getInputArgumentString("real_device_address")
         , getInputArgumentString("port_name")
         , getInputArgumentString("controller_name")
         , (int)getInputArgumentLong("connection_value")
         , (int)getInputArgumentLong("queue_memory_limit")
         , (int)getInputArgumentLong("routing_value")
         , (int)getInputArgumentLong("port_type")
         , (int)getInputArgumentLong("update_system_config_indicator")
         , getInputArgumentString("system_config_name")
         , getInputArgumentString("system_config_type")
         , getInputArgumentString("parm_disk_owner")
         , getInputArgumentString("parm_disk_number")
         , getInputArgumentString("parm_disk_password")
         , getInputArgumentString("alt_system_config_name")
         , getInputArgumentString("alt_system_config_type")
         , getInputArgumentString("alt_parm_disk_owner")
         , getInputArgumentString("alt_parm_disk_number")
         , getInputArgumentString("alt_parm_disk_password")
         , (int)getInputArgumentLong("gvrp_value")
         , getInputArgumentString("mac_id")
	);
        execute(pigfunc,requestor,response);
        return response;
    }
       
}
