package com.softwoehr.pigiron.access.paramstructs;

import com.softwoehr.pigiron.access.*;

/**
 * AdapterArray implements the page_range_array from Virtual_Adapter_Query
 * @see com.softwoehr.pigiron.functions.Virtual_Adapter_Query
 * @see com.softwoehr.pigiron.access.paramstructs.AdapterStruct
 */
public class AdapterArray extends VSMArray {

    /**
     * Create a modelled-for-read instance with a specified formal name.
     * @param formalName the formal name
     * @return the modelled instance.
     */
    public static AdapterArray modelArray(String formalName) {
        AdapterArray result = new AdapterArray();
        result.add(new AdapterStructCounted(null, "adapter_struct_counted"));
        result.setFormalName(formalName);
        return result;
    }

    /**
     * Create an instance by copying the value from a like instance, and
     * assign also the formal name.
     * @param value a like instance to copy from
     * @param formalName the formal name
     */
    public AdapterArray(VSMArray value, String formalName) {
        super(value, formalName);
    }

    /**
     * Create an instance by copying the value from a like instance.
     * @param value a like instance to copy from
     */
    public AdapterArray(VSMArray value) {
        super(value);
    }

    /**
     * Create an instance of undefined value.
     */
    public AdapterArray() {
    }
}

/* End of autogenerated code */

